services:
  - type: web
    name: akova-jobportal-backend
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://akovadev:Akova%402025@akova.glxh1wv.mongodb.net/jobportal?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: Xupj1JAUQA1vPNcex4SDcOqqypZ6LlmX5UmwNpBkacY
      - key: PORT
        value: 10000